# Generated by Django 3.0 on 2021-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200402_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_field',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
